name: null

channels:
  - conda-forge
  - nodefaults

dependencies:
  - gh
  - git
  - git-lfs
  - jupyterlab
  - jupyterlab-lsp
  - nbgitpuller
  - pip
  - pip:
    - -r requirements.txt
  - python
  - python-lsp-server
